# Header
menu:
  Design: /
  Animation: /animation
  Photo: /photo

menund:
  Note: /note
  About: /about

# Default post title
default_post_title: Untitled

# Default post cover index page
default_cover_index: "http://placehold.it/450x450"




# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  #disqus_shortname:
  # Facebook comments
  facebook:
    appid: 123456789012345
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url:
facebook_url: https://www.facebook.com/
email_url: mailto:zhukileiyu@gmail.com
googleplus_url: https://plus.google.com
dribble_url: https://dribbble.com
rss_url: